### ISSUE TITLE
failed to login: challenge_required

### ISSUE THREAD

**Issue by marceloavilaoliveira** [obalunenko/instadiff-cli#108]
When I execute:

`instadiff-cli followings --list
`

I got the following fatal error:

`FATA[2022-06-06 22:33:48] service setup: make client: failed to login: : challenge_required
`

The application should work the Instagram challenge_required issue, right? What could be wrong?

Thanks a lot for your support.

![S2022_06_06-22_38_15](https://user-images.githubusercontent.com/20242819/172277500-b9a570ae-6913-49a3-8541-a70cb7931e60.png)

**Comment by obalunenko** [comment]
@marceloavilaoliveira Please try a newer version [v0.16.0](https://github.com/obalunenko/instadiff-cli/releases/tag/v0.16.0)

**Comment by obalunenko** [comment]
Thanks @marceloavilaoliveira for your detailed feedback.
I'll take a look on it.
I have some questions:
- Have you set up an application for 2fa (like 1password, Google Auth)? 
- Have you check a screenshot that is mentioned on logs?

**Comment by marceloavilaoliveira** [comment]
Hi @obalunenko 

Actually, I didn't have set 2FA on Instagram yet, so I configured it to use Google Authenticator, and it worked:

![S2022_06_07-10_12_29](https://user-images.githubusercontent.com/20242819/172510216-feff7fe9-b355-4edd-9344-1db807603344.png)

The application listed correctly all the followings. Unfortunately, in the end, one error was presented:

![S2022_06_07-10_19_06](https://user-images.githubusercontent.com/20242819/172510712-1c02c3c4-5317-4eef-ae18-d603a17ce57e.png)

But this didn´t compromise the result.

I'm doing more tests but I think the application is working pretty well now. I'll let you know.

**Comment by marceloavilaoliveira** [comment]
Hi @obalunenko,

I executed some other commands and everything seems to be working as expected. The only "weird" thing is the "405 Method Not Allowed" error at the end of execution.

Thank you very much for your help, and congratulations on your application.

Let me take this opportunity and ask a few questions:

1) Why does Instagram show "Samsung SM-G975F" in the Login Activity (I'm using the application on a Linux computer)? 

![image](https://user-images.githubusercontent.com/20242819/172688015-91921581-045f-4ec8-ac1f-1e4084191850.png)

2) Can I use usernames in the whitelist or must I use numbers?

3) Is there any instructions on how to build/install from code?

Thanks in advance.

**Comment by obalunenko** [comment]
Hi @marceloavilaoliveira,

Thanks a lot for the testing and for your feedback.

Answering your questions:

1. This application utilizes the mobile API, a device is also emulated. That's why you can see  "Samsung SM-G975F" as user-agent in the Login Activity.
2. Yep, I've added the support of both in [new version](https://github.com/obalunenko/instadiff-cli/releases/tag/v1.0.0)
3. I added information to the README how to develop and test locally. In brief, just use `make build` command in the root of repository.

**Comment by marceloavilaoliveira** [comment]
Unfortunately, the v1.0.1 didn't work for me.

Trying to clean followers:

```
> instadiff-cli clean-followers
...
INFO[08-06-2022 22:20:58] Logged-in                                     username=xxxxx
INFO[08-06-2022 22:21:02] Cleaning from not mutual followings...        cmd=clean_not_mutual
INFO[08-06-2022 22:21:41] Exit...                                      
FATA[08-06-2022 22:21:41] Failed to run                                 error="clean notmutual: get not mutual followers: get followers: make users list: users iterate: No more posts availible, page end has been reached"
```
Trying to list followings:

```
> instadiff-cli followings --list
...
INFO[08-06-2022 22:22:41] Logged-in                                     username=xxxxx
INFO[08-06-2022 22:22:53] Exit...                                      
FATA[08-06-2022 22:22:53] Failed to run                                 error="get followings: make users list: users iterate: Error while calling friendships/xxxxx/following/, status code 560:  (560 )"
```

**Comment by obalunenko** [comment]
Yeah, that's my bad about "No more posts available" error - late night coding issue 😄 
FIxed this in [v1.0.2](https://github.com/obalunenko/instadiff-cli/releases/tag/v1.0.2)

About `status code 560` - this seems to be an Instagram server issue, smth went wrong on their side at that moment.

**Comment by marceloavilaoliveira** [comment]
Now it worked pretty well.

Thanks a lot.

**Comment by obalunenko** [comment]
Thank you, @marceloavilaoliveira, for your feedback and help to improve the application. 
I appreciate that^^

**Comment by Davincible** [comment]
@marceloavilaoliveira did you eventually get past the challenge with the chromium browser, or how did you resolve it?

**Comment by marceloavilaoliveira** [comment]
From time to time, the challenge appears but I was not able to make it works yet. AFAIR I click on the "Submit" button and nothing happens (I'm not sure about this). Every time this happens my account is blocked and I have to set a new password. I'll pay more attention to the details the next time it happens.

**Comment by Davincible** [comment]
Hm interesting. Next time it happens, could you open your dev tools when you get the browser, and check the response to the request that submits the code? >> does it go through or not

What you could also try is after submitting the code, and the request has gone through, manually closing the browser window, and checking if it works. Could also be that it just doesn't redirect properly after submitting the code

**Comment by marceloavilaoliveira** [comment]
Today some different happened... An Instagram message said my account was blocked and sent me a 6-digit code, I typed the code and clicked on "Submit", then it asked me to set a new password, I set it, and a new window opened saying "Open xdg-open? https://i.instagram.com wants to open this application", I clicked on "Open xdg-open" button but nothing happens. Then I opened the Chrome "Inspect" and when I was trying to discover something, the window just closed.

The following message is showed in my terminal:

```
...
INFO[18-09-2022 15:39:28] Cleaning from not mutual followings...        cmd=clean-followings
Fetching followers▌Request Status Code 400: fail, challenge_required
Encountered a captcha challenge, goinsta will attempt to open the challenge in a headless chromium browser, and take a screenshot. Please report the details in a github issue.
INFO[18-09-2022 15:44:41] Exit...                                      
FATA[18-09-2022 15:44:41] Failed to run                                 error="get not mutual followers: get followers: make users list: users iterate: failed to process challenge automatically with: context deadline exceeded"
```

**Comment by Davincible** [comment]
Hmm yeah I see. For now it's best to solve challenges directly in the app.

The difficulty with making this work is that it's very hard to reproduce often, and make it work reliably.

Did it give you a reason for the block ?

**Comment by marceloavilaoliveira** [comment]
After that, when I tried to use the app, it said that some automation (or any other term like that) is trying to use my account and, because of it, my account was blocked. I had to resolve two challenges and change the password. :-(

So, when the instadiff-cli asks for a challenge, is it better to use the app first to resolve the issue?

**Comment by Davincible** [comment]
Hm I see. Yes, it is

**Comment by obalunenko** [comment]
@Davincible could these new query parameters added in version v3.2.4 possibly trigger Meta ML AI that these requests are send via automation script, not from the app?
commits
- https://github.com/Davincible/goinsta/commit/27d9fde1d6cacd50780b8e79789a1f0fb9a94f99
- https://github.com/Davincible/goinsta/commit/1837cc64b613fa26ea92ab975cca97cf8dda7c74

**Comment by Davincible** [comment]
I don't think it's the get params. I expect it's related to the update to `v250.0.0.21.109`, where perhaps they implemented either extra requests in the login procedure, or added extra headers, and detect that they are missing. Just a hunch though.

It's possible to add them in, just requires more work.

If you have the time I could teach you how I go about analyzing it and we could look at it together, two pairs of eyes are always better than one.

**Comment by obalunenko** [comment]
@Davincible Sure, I'll gladly help you

**Comment by Davincible** [comment]
@obalunenko how can I best reach you? (telegram, discord, smth else?)

**Comment by obalunenko** [comment]
@Davincible telegram is my primary channel for communication

https://t.me/obalunenko
