### ISSUE TITLE
config_path default is not working

### ISSUE THREAD

**Issue by marceloavilaoliveira** [obalunenko/instadiff-cli#167]
When I run, for example:

`instadiff-cli clean-followers
`

I got:

`FATA[0000] Failed to run                                 error="Required flag \"config_path\" not set"
`

If I add "--config_path .config.json" flag the command executes just fine.

instadiff-cli version 1.7.1

**Comment by obalunenko** [comment]
Hi @marceloavilaoliveira !
Thank you for your feedback! I fixed the behaviour and you can try a fresh release to check it.

**Comment by marceloavilaoliveira** [comment]
I just tested the 1.7.2 version. It's working just fine. Thanks.
