### ISSUE TITLE
Doubt about clean-following command strategy

### ISSUE THREAD

**Issue by marceloavilaoliveira** [obalunenko/instadiff-cli#168]
I frequently use the "clean-followings" command, which works just fine, but I would like to know: It unfollows the FIRST "n" not mutual followings or the LAST ones? Or does it choose the not mutual followings aleatorily?

**Comment by obalunenko** [comment]
Hi @marceloavilaoliveira !
Since #171 PR will be merged the following algorithm will be used: it will unfollow FIRST "n" not mutual followings sorted by their IDs in descending order.

**Comment by marceloavilaoliveira** [comment]
Uhm... just to be sure: this "ID" is related to when the user created his/her Instagram account, right? Newer accounts have bigger IDs, correct?

Actually, I would like to know if it's possible to unfollow the not mutual followings based on when the user was followed by me. Not mutual followings I follow the longest should be unfollowed first. There is a greater chance that the newer ones will become followers yet.

I don't know if I was able to make myself clear.

**Comment by obalunenko** [comment]
Yeah, these ID I receive from instagram, so seems that their logic for these ID values is what you've described.

I see.. Well, I double checked the SDK that I'm using and unfortunately didn't find any mention of date for following

**Comment by marceloavilaoliveira** [comment]
I really thought there was no way to implement this. Anyway, thanks a lot for your attention, I think the algorithm you started to use will be a good improvement.

**Comment by obalunenko** [comment]
HI @marceloavilaoliveira !
I have a good news) I contacted with owner of SDK that I'm using in my tool and he implemented functionality to get

**Comment by obalunenko** [comment]
https://github.com/Davincible/goinsta/issues/33

**Comment by obalunenko** [comment]
Hi @marceloavilaoliveira !
I've added the ordering by earliest date for following list, that means that now not mutual followings you follow the longest will  be unfollowed first.
Could you please check the latest version v1.9.1?
