### ISSUE TITLE
Instagram username issue

### ISSUE THREAD

**Issue by marceloavilaoliveira** [obalunenko/instadiff-cli#183]
Hello,

When I execute the "instadiff-cli" program it always asks "What is your username?". Is it possible to tell the Instagram username via a parameter or via the config file?

Thanks a lot.

Best regards.

**Comment by obalunenko** [comment]
Hello @marceloavilaoliveira ! 
I added requested changes in [v1.10.0] (https://github.com/obalunenko/instadiff-cli/releases/tag/v1.10.0)

**Comment by marceloavilaoliveira** [comment]
I just tested it, and it worked pretty well. Thanks a lot.

**Comment by obalunenko** [comment]
Thanks for testing, @marceloavilaoliveira ! 
I have a question, do you steel have issues with block from Instagram?

**Comment by marceloavilaoliveira** [comment]
I had some issues again but I think this kind of problem is related to executing too many actions (follow/unfollow) in a short space of time. I'm now limiting the number of interactions and it seems to be better now.
