### ISSUE TITLE
User not found error

### ISSUE THREAD

**Issue by marceloavilaoliveira** [obalunenko/instadiff-cli#188]
When running instadiff-cli with "follow" or "unfollow" parameters, one of the "--user USER" parameters may contain an incorrect user and the script exits with a "User not found" error as shown below.

![S2022_10_17-15_54_52](https://user-images.githubusercontent.com/20242819/196263516-1679de9b-edb7-4064-afc5-1fb02cc451c1.png)

It would be better if the script skipped the problematic user and ran to the end of the user list. In other words, the script should just throw a warning instead of an error.

Do you think this is feasible?

**Comment by obalunenko** [comment]
Hi @marceloavilaoliveira ! 
Thank you for your feedback. It's a fare point, and this is rather easy to implement. I'll add this behavior soon in next version

**Comment by obalunenko** [comment]
Hi @marceloavilaoliveira !
I've added the requested changes in new release [v1.10.1](https://github.com/obalunenko/instadiff-cli/releases/tag/v1.10.1)

**Comment by marceloavilaoliveira** [comment]
Grat, it worked pretty well.

Thanks a lot for all your support.
