### ISSUE TITLE
Unable to increase the count of usernames using the flag unfollow-users

### ISSUE THREAD

**Issue by 1ndev-ui** [obalunenko/instadiff-cli#274]
cmd=unfollow-users username=xxxxxxxx
cmd=unfollow-users count=1
cmd=unfollow-users count=1 operation="unfollow users"

Any suggestions?

**Comment by obalunenko** [comment]
Hi @1ndev-ui ! Thank you for your issue
Could you please provide me the command how you run it?
It should be something like this according to help:
`instadiff-cli unfollow-users --help`

`instadiff-cli unfollow-users --users u1,u2,u3`

**Comment by 1ndev-ui** [comment]
Ahhh adding the comma solved the issue, thank you for the quick feedback. much appreciated @obalunenko
